### PR TITLE
[AFP-2121] Configure Permissions Message

### PR DESCRIPTION
**Pull request by thebriando**
Adds a `permissionsMessage` field to the config to configure the message when a user views the queue tab or history tab and does not have admin access.

### CODE REVIEW

**Comment by gardnerjack** [comment]
Awesome stuff, don't worry about the integration tests failing. You don't actually need to run them in this case because we have this weird set up where you need to deploy the changes first before running the tests (so it's pointless to do it here before doing that).
I'll take you through that process when we deploy this change :)

**Review by lukebatchelor — APPROVED** [review]
Awesome!!! Looks great. 

For our message when you deploy, let's have it be something like "please ping !disturbed in #atlassian-frontend if you require access to land"

**Comment by gardnerjack** [comment]
I reckon that we should have a default permissions message, which would reduce upgrade pain. We don't really have a proper way of doing this (although we probably should), so maybe in `Config.ts` include something like this:

```
if (!config.permissionsMessage) {
  config.permissionsMessage = 'Contact an admin...
}
```

Then you would have to update some of the types so that you can assume existence of the message.

**Review by gardnerjack — CHANGES_REQUESTED** [review]
I reckon that we should have a default permissions message, which would reduce upgrade pain. We don't really have a proper way of doing this (although we probably should), so maybe in `Config.ts` include something like this:

```
if (!config.permissionsMessage) {
  config.permissionsMessage = 'Contact an admin...
}
```

Then you would have to update some of the types so that you can assume existence of the message.

**Comment by gardnerjack** [comment]
To add on to my comment above, I think it would be great to actually have some proper config validation with defaults and stuff. I know [convict](https://github.com/mozilla/node-convict/tree/master/packages/convict) provides this pretty well. But [joi](https://github.com/sideway/joi) is a dev dep for testing purposes so maybe that will offer a good option as well. Don't need to do it for this but just wanted to document my thoughts.

**Review by gardnerjack — APPROVED** [review]

**Pull request merged**
